name: Deploy to AWS EKS (OIDC)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy"
        required: false
        default: "dev"
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    environment: dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_EKS_OIDC }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER }} --region ${{ secrets.AWS_REGION }}

      - name: Deploy to EKS
        run: |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm dependency build
          helm install simple-app-0-0-1 . # --dry-run --debug .
